[   [   (   1,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'fd',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > xc_archi > update lgen',
            None,
            None),
        (   2,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'fd',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > xc_archi > update netgen',
            None,
            None),
        (   3,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'fd',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > xc_archi > update adl (generate kad + dly + zan)',
            None,
            None),
        (   4,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'fd',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > xc_archi > modify traits',
            None,
            None),
        (   5,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'pg',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > update lgen',
            None,
            None),
        (   6,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'pg',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > update netgen',
            None,
            None),
        (   7,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'pg',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > update adl (generate kad + dly + zan)',
            None,
            None),
        (   8,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'pg',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > modify traits',
            None,
            None),
        (   9,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'pg',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > update delay estimator for register file (adl)',
            None,
            None),
        (   10,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'fd',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > update lgen',
            None,
            None),
        (   11,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'fd',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > update netgen',
            None,
            None),
        (   12,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'fd',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > update adl (generate kad + dly + zan)',
            None,
            None),
        (   13,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'fd',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > modify traits',
            None,
            None),
        (   14,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'pg',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'zarkitek > time scale adjustment',
            None,
            None),
        (   15,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'fd',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'builder > introduce 18K ram',
            None,
            None),
        (   16,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'fd',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'builder > introduce regiser file',
            None,
            None),
        (   17,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'fd',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'builder > test & integration',
            None,
            None),
        (   18,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'lj',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'flat_place > dpram18k & register file in plugin',
            None,
            None),
        (   19,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'lj',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'flat_place > test & integration',
            None,
            None),
        (   20,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'hc',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'flat_route > dpram18k & register file integration > update plugin > orientate functions > implementation',
            None,
            None),
        (   21,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'hc',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'flat_route > dpram18k & register file integration > update plugin > orientate functions > test & integration',
            None,
            None),
        (   22,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'hc',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'flat_route > dpram18k & register file integration > update plugin > materialize functions > implementation v4x4',
            None,
            None),
        (   23,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'hc',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'flat_route > dpram18k & register file integration > update plugin > materialize functions > test & integration',
            None,
            None),
        (   24,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'pg',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'verification > 18K ram & regfile integration > update verilog model',
            None,
            None),
        (   25,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'pg',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'verification > 18K ram & regfile integration > simulation with verification model',
            None,
            None),
        (   26,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'gs',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'verification > 18K ram & regfile integration > update timming model (.lib)',
            None,
            None),
        (   27,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'gs',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'verification > 18K ram & regfile integration > update pluging ztv',
            None,
            None),
        (   28,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'gs',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > enable_asynchonous_reset',
            None,
            None),
        (   29,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'gs',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > asynchonous_path_domain',
            None,
            None),
        (   30,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'gs',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > constrain > generated_clock',
            None,
            None),
        (   31,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'gs',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > exception > subgraph extraction (no -through)',
            None,
            None),
        (   32,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'gs',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > exception > false paths',
            None,
            None),
        (   33,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'gs',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > exception > false path documentation',
            None,
            None),
        (   34,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'gs',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > exception > multicycle paths',
            None,
            None),
        (   35,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'gs',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > exception > min/max delay',
            None,
            None),
        (   36,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'lj',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > transfer sdc a.p.i  to top_shell',
            None,
            None),
        (   37,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'gs',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > transfer sdc a.p.i  to top_shell',
            None,
            None),
        (   38,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'gs',
            u'testuser',
            None,
            None,
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > add command',
            None,
            None),
        (   39,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'gs',
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'timing annalysis > test & integration',
            None,
            None),
        (   40,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'ac',
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'Optimization > clusterization',
            None,
            None),
        (   41,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'lj',
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'Optimization > clusterization',
            None,
            None),
        (   42,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'ac',
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'release > integration, quality & regression',
            None,
            None),
        (   43,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'fd',
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'release > integration, quality & regression',
            None,
            None),
        (   44,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'gs',
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'release > integration, quality & regression',
            None,
            None),
        (   45,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'hc',
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'release > integration, quality & regression',
            None,
            None),
        (   46,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'lj',
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'release > integration, quality & regression',
            None,
            None),
        (   47,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'pg',
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'release > integration, quality & regression',
            None,
            None)],
    [   (1, u'effort', None),
        (2, u'effort', None),
        (3, u'effort', None),
        (4, u'effort', None),
        (5, u'effort', None),
        (6, u'effort', None),
        (7, u'effort', None),
        (8, u'effort', None),
        (9, u'effort', None),
        (10, u'effort', None),
        (11, u'effort', None),
        (12, u'effort', None),
        (13, u'effort', None),
        (14, u'effort', None),
        (15, u'effort', None),
        (16, u'effort', None),
        (17, u'effort', None),
        (18, u'effort', None),
        (19, u'effort', None),
        (20, u'effort', None),
        (21, u'effort', None),
        (22, u'effort', None),
        (23, u'effort', None),
        (24, u'effort', None),
        (25, u'effort', None),
        (26, u'effort', None),
        (27, u'effort', None),
        (28, u'effort', None),
        (29, u'effort', None),
        (30, u'effort', None),
        (31, u'effort', None),
        (32, u'effort', None),
        (33, u'effort', None),
        (34, u'effort', None),
        (35, u'effort', None),
        (36, u'effort', None),
        (37, u'effort', None),
        (38, u'effort', None),
        (39, u'effort', None),
        (40, u'effort', None),
        (41, u'effort', None),
        (42, u'effort', None),
        (43, u'effort', None),
        (44, u'effort', None),
        (45, u'effort', None),
        (46, u'effort', None),
        (47, u'effort', None)],
    [],
    [],
    []]