[   [   (   1,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'newuser1',
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'sum1',
            None,
            None),
        (   2,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'newuser2',
            u'testuser',
            None,
            None,
            None,
            u'assigned',
            None,
            u'sum2',
            None,
            None),
        (   3,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'newuser3',
            u'testuser',
            None,
            None,
            None,
            u'accepted',
            None,
            u'sum3',
            None,
            None)],
    [   (1, u'mycustomfield', None),
        (2, u'mycustomfield', None),
        (3, u'mycustomfield', None)],
    [],
    [],
    []]