#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2005-2008 Alex Thomas
# Copyright (C) 2010-2017 Ryan J Ollos <ryan.j.ollos@gmail.com>
# All rights reserved.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution.
#

import sys
from trac.env import Environment

assert len(sys.argv) == 2, "\n\nusage: %s <trac-environment>\n\nRe-index repository." % sys.argv[0]

e = Environment(sys.argv[1])
from tracreposearch.indexer import Indexer
indexer = Indexer(e)
