[   [   (   1,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'me',
            u'me',
            None,
            None,
            None,
            u'new',
            None,
            u'sum1',
            None,
            None),
        (   2,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            None,
            None,
            None,
            None,
            None,
            u'new',
            None,
            u'sum2',
            None,
            None)],
    [(1, u'mycustomfield', None), (2, u'mycustomfield', None)],
    [],
    [],
    []]