[   [   (   1,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'ac',
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'release > integration, quality & regression',
            None,
            None),
        (   2,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'fd',
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'release > integration, quality & regression',
            None,
            None),
        (   3,
            u'task',
            1190909220000000L,
            1190909220000000L,
            None,
            None,
            u'major',
            u'gs',
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'release > integration, quality & regression',
            None,
            None)],
    [(1, u'effort', None), (2, u'effort', None), (3, u'effort', None)],
    [],
    [],
    []]