[   [   (   1,
            u'task',
            1190909220000000,
            1190909220000000,
            u'mycomp',
            None,
            u'mypriority',
            u'me',
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'sum1',
            None,
            None),
        (   2,
            u'task',
            1190909220000000,
            1190909220000000,
            u'yourcomp',
            None,
            u'yourpriority',
            u'you',
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'sum2',
            None,
            None)],
    [   (1, u'mycustomfield', u'mycustomfield1'),
        (2, u'mycustomfield', u'customfield2')],
    [],
    [(u'priority', u'mypriority', u'6'), (u'priority', u'yourpriority', u'7')],
    [(u'mycomp', None, None), (u'yourcomp', None, None)]]
