[   [   (   1,
            u'task',
            1190909220000000,
            1190909220000000,
            None,
            None,
            u'major',
            None,
            u'testuser',
            None,
            None,
            None,
            u'new',
            None,
            u'test1',
            None,
            None)],
    [(1, u'mycustomfield', None)],
    [],
    [],
    []]
